#!/bin/bash

user=$1
hash=$2

if [[ ` ./root/lib/correct $user` == 'nie' ]]; then
	echo err
	exit
fi
if [[ `awk -F: '/^'$user':/ {print $2}' ./root/users/passwd` == $hash ]]; then
	echo ok
else
	echo err
fi
