#!/bin/bash

. ./root/config.gen

user=$1
task=$2

lang=`egrep "^$task:" ./root/users/homes/$user/submissions | awk -F: '//{printf("%s\n", $2)}'`

dir=./root/users/homes/$user/$task

cmd=$(./root/lib/get_var compile_${lang}_cmd | sed "{s|{exe}|$dir/$task.e|};{s|{src}|$dir/$task|}")

$cmd
