#!/bin/bash

user=$1

if [[ `grep "$user" ../users/passwd` ]]; then
	echo -n 'New password: '
	read pass
	pass=`../lib/hash $pass`
	awk -F: '/^'$user':/{printf("%s:%s\n", $1, "'$pass'")}; !/^'$user':/{printf("%s\n", $0)}' ../users/passwd > ../users/.passwd
	mv ../users/.passwd ../users/passwd
else
	echo No such user\!
	exit 1
fi
