#!/bin/bash

user=$1

if [[ `grep "$user" ./root/users/passwd` ]]; then
	echo -n 'New password: '
	read pass
	pass=`./root/lib/hash $pass`
	awk -F: '/^'$user':/{printf("%s:%s\n", $1, "'$pass'")}; !/^'$user':/{printf("%s\n", $0)}' ./root/users/passwd > ./root/users/.passwd
	mv ./root/users/.passwd ./root/users/passwd
else
	echo No such user\!
	exit 1
fi
