#!/bin/bash

function usage()
{
	echo "Usage: ./submit username task_code language"
}

if [[ $# != 3 ]]; then
	usage
	exit 1
fi

user=$1
task=$2
lang=$3

file=./root/users/homes/$user/$task/$task.$lang

mkdir -p ./root/users/homes/$user/$task
cat  > $file

touch ./root/users/homes/$user/submissions
cat ./root/users/homes/$user/submissions | egrep -v "^$task:" > ./root/users/homes/$user/.submissions
echo $task:$lang:`date +%s`:- >> ./root/users/homes/$user/.submissions
mv ./root/users/homes/$user/.submissions ./root/users/homes/$user/submissions
