#!/bin/bash

user=$1

if [[ `./root/lib/correct "$user"` == "nie" ]]; then
	echo Incorrect username\!
	exit 1
fi
	
touch ./root/users/passwd

if [[ `grep $1 ./root/users/passwd` ]]; then
	echo User already exists\!
	exit 1
fi

pass=x
if [[ -n $2 ]]; then
	if [[ -z $3 ]]; then
		pass=`./root/lib/hash $2`
	else
		pass=$2;
	fi
fi

echo $user:$pass >> ./root/users/passwd

mkdir -p ./root/users/homes/$user
touch ./root/users/homes/$user/submissions
./root/scripts/genconfig
