#!/bin/bash

user=$1

if [[ `grep $user ./root/users/passwd` ]]; then
	grep -v $user ./root/users/passwd > ./root/users/.passwd
	mv ./root/users/.passwd ./root/users/passwd
else
	echo No such user\!
	exit 1
fi

rm -fr ./root/users/homes/$user
./root/scripts/genconfig
