#!/bin/bash

. ./root/config

cat ./root/config > ./root/config.gen

for task in $tasks; do
	cat ./root/tasks/$task/tests.conf | sed "{s/^/${task}_/}" >> ./root/config.gen

	echo ${task}_pretests_points=\"$(for pretest in `./root/lib/get_var ${task}_pretests`; do echo -n "0 "; done)\" >> ./root/config.gen

	for kind in tests pretests; do 
		for what in limits points; do
			./root/lib/get_var ${task}_${kind}_${what} > ./root/.tmp
			vars=$(for var in `./root/lib/get_var ${task}_${kind}`; do echo -n "${task}_${what}_${var} "; done) 
			read $vars < ./root/.tmp
			export $vars
			for var in $vars; do
				echo ${var}=\"${!var}\" >> ./root/config.gen
			done
			rm -fr ./root/.tmp
		done
	done

	echo users=\"`awk -F: '//{printf("%s ", $1)}' ./root/users/passwd`\" >> ./root/config.gen

done


