#!/bin/bash

read cmd login hash

if [[ -z $login ]]; then
	echo Protocol error
	exit
fi
if [[ -z $hash ]]; then
	echo Protocol error
	exit
fi

if [[ $cmd == 'CREATE' ]]; then
	./root/lib/useradd $login $hash hash
else
	if [[ $cmd == 'LOGIN' ]]; then
		if [[ `./root/lib/authorize $login $hash` == 'ok' ]]; then
			./root/lib/user_shell $login
		else
			echo Authentication error
		fi
	else
		echo Protocol error
	fi
fi
