#!/bin/bash

function usage()
{
	echo "Usage: ./userdel name"
}

if [[ -z $1 ]]; then
	usage
	exit 1
fi

user=$1

if [[ `grep $user ../users/passwd` ]]; then
	grep -v $user ../users/passwd > ../users/.passwd
	mv ../users/.passwd ../users/passwd
else
	echo No such user\!
	exit 1
fi

rm -fr ../users/homes/$user
./genconfig
